version: 0.2

phases:
  install:
    commands:
      - echo "Upgrading pip"
      - pip install --upgrade pip
      - echo "Upgrading AWS CLI, requires 1.18.38 or later"
      - pip install awscli --upgrade --user
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - bash build-all.sh delete-ok
  post_build:
    commands:
      - echo Build completed on `date`

